/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorUsuario;
import Modelo.ClaseUsuario;
import Modelo.ImagenFondo;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ghust
 */
public class Incidencias extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Incidencias.class.getName());

    /**
     * Creates new form Incidencias
     */
    ClaseUsuario userSesion;
    ImagenFondo imgFondo;
    private int idActividadRef;
    private int idUbicacionRef;

    public Incidencias(ClaseUsuario usuario, int idAct, String nombreAct, String codigoUbi, String direccion, int idUbi) {
        imgFondo = new ImagenFondo("src/imagenes/fondoFRM.jpg");
        this.setContentPane(imgFondo);
        initComponents();
        idActividadRef = idAct;
        idUbicacionRef = idUbi;
        userSesion = usuario;
        txtActividadInfo.setText("Actividad: " + nombreAct);
        txtCodigoInfo.setText("Codigo: " + codigoUbi);
        lblDireccionInfo.setText("Direccion: " + direccion);
        lblUsuarioReporta.setText("Reporta: " + userSesion.getNombre());
        lblNombreUsuario.setText("Bienvenido: " + userSesion.getNombre() + " " + userSesion.getApellido() + "  Rol: " + userSesion.getRol());
        String rol = userSesion.getRol();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBtITULO = new javax.swing.JLabel();
        jlbTipoIncidencias = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jlbDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtaDescripcion = new javax.swing.JTextArea();
        jbnAgregar = new javax.swing.JButton();
        jbnRegresar = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUsuarioReporta = new javax.swing.JLabel();
        txtActividadInfo = new javax.swing.JLabel();
        txtCodigoInfo = new javax.swing.JLabel();
        lblDireccionInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLBtITULO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JLBtITULO.setForeground(new java.awt.Color(86, 191, 22));
        JLBtITULO.setText("REGISTRO DE INCIDENCIAS");

        jlbTipoIncidencias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbTipoIncidencias.setForeground(new java.awt.Color(86, 191, 22));
        jlbTipoIncidencias.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2FAM (2/A FASE A MUPI)", "2FAP (2/A FASE A POSTES)", "AHS (ACRILICO HUMO SUELTO)", "A (APAGADO)", "AT (ATERRIZADO)", "CAHR (CAMBIAR ACRILICO HUMO ROTO)", "CAHRZ (CAMBIAR ACRILICO HUMO ROTO ZAP.)", "BAL (CAMBIAR BALANCIN)", "CBAL (CAMBIAR BALASTRA)", "CB (CAMBIAR BANCA)", "CBZP (CAMBIAR BANCA MOD. ZAP.)", "CAPCH (CAMBIAR CAPOTA CHOCADA)", "CAZXG (CAMBIAR CAPOTA MOD. ZAPOPAN POR MOD. GDL)", "CCH (CAMBIAR CHUPON)", "CDR (CAMBIAR DIFUSOR ROTO)", "CDRZP (CAMBIAR DIFUSOR ROTO MOD. ZAPOPAN)", "CETR (CAMBIAR ESPARRAGO Y TUERCA REMACHE)", "CMP (CAMBIAR MARCO PERIMETRAL)", "CMEZC (CAMBIAR MARCO ELEC.ZAP.CHI.)", "CMEZG (CAMBIAR MARCO ELEC.ZAP.GDE.)", "CME (CAMBIAR MARCO ELECTRICO)", "CMEZG (CAMBIAR MARCO ELECTRICO MOD.ZAP.GDE.)", "CM (CAMBIAR MUPI)", "CPIT (CAMBIAR PIEDRA INFERIOR POR TAPA)", "CPS (CAMBIAR PIEDRA SUPERIOR)", "CPST (CAMBIAR PIEDRA SUPERIOR POR TAPA)", "CP (CAMBIAR POSTE)", "CTI (CAMBIAR TAPA INFERIOR)", "CTS (CAMBIAR TAPA SUPERIOR)", "CTR (CAMBIAR TUERCAS REMACHES)", "CVD (CAMBIAR VENTANA POR DESGASTE)", "CMEZC (CAMBIAR MARCO ELECTRICO MOD.ZAP.CHI.)", "CAPCHZ (CAPOTA CHOCADA MOD. ZAPOPAN)", "CHL (CHECAR LINEAS)", "COCH (COBERTIZO CHOCADO)", "CTRM (COLOCAR TUERCA REMACHE P/M.E.)", "CTRV (COLOCAR TUERCA REMACHE EN VENTANA)", "CPLL (CONTENEDOR DE PILAS LLENO)", "FA (FALTA ANTEPECHO)", "FB (FALTA BISAGRA)", "FCAP (FALTA CAPOTA)", "FCH (FALTA CHUPON)", "FCOB (FALTA COBERTIZO)", "FAH (FALTA CRILICO HUMO)", "FD (FALTA DIFUSOR)", "FFT (FALTA FOTOCELDA)", "FMU (FALTA MUPI)", "FPB (FALTA PARABUS)", "FPI (FALTA PIEDRA INFERIOR)", "FPS (FALTA PIEDRA SUPERIOR)", "FRC (FALTA REMATE CORTO)", "FRL (FALTA REMATE LARGO)", "FRM (FALTA REMATE MEDIANO)", "FTI (FALTA TAPA INFERIOR)", "FTS (FALTA TAPA SUPERIOR)", "FCH (FALTAN CHUPONES)", "FE (FALTAN EJES DE AMORTIGUADOR)", "FL (FALTAN LENGUETAS)", "LS (LENGÜETA SUELTA)", "MES (MARCO ELECTICO SUELTO)", "MCAG (MONTAR CAPOTA MOD. GDL)", "MCAZ (MONTAR CAPOTA MOD. ZAP.)", "MC (MONTAR COBERTIO)", "MMG (MONTAR MUPI MOD. GDL.)", "MMZ (MONTAR MUPI MOD. ZAPOPAN)", "MPCG (MONTAR PARABUS COMPLETO MOD. GDL.)", "MPCZ (MONTAR PARABUS COMPLETO MOD. ZAP.)", "MCH (MUPI CHOCADO)", "OCU (OCULTAR ACOMETIDA)", "PAR (PARCIAL (LUZ))", "PIR (PIEDRA INFERIOR ROTA)", "P (PODA)", "PESP (PONER ESPARRAGO)", "PTR (PONER PTR)", "PG (POSTE GOLPEADO)", "PRE (PRENDIDO)", "RECP (RECOLECTAR PILAS)", "RME (REMACHAR MARCO ELECTRICO)", "RPME (REMACHAR PLACA DEL MARCO ELECTRICO)", "RAC (REPAPAR ACOMETIDA)", "RM (RETIRAR MUPI)", "RPS (RETIRAR PILAS DEL SISTEMA)", "RL (REUBICAR LETRERO)", "SG (SERVICIO GENERAL (LEVAS, CERRAR MUEBLE))", "SB (SOLDAR BANCA)", "SCM (SOLDAR COPA DE MUPI)", "STI (SOLDAR TAPA INFERIOR)", "STS (SOLDAR TAPA SUPERIOR)", "TIS (TAPA INFERIOR SUELTA)", "TSS (TAPA SUPERIOR SUELTA)", "VC (VENTANA CAIDA)", "VA (VENTANA CON ACIDO)", "VAZPC (VENTANA CON ACIDO MOD.ZAP.CHI.)", "VAZPG (VENTANA CON ACIDO MOD.ZAP.GDE.)", "VD (VENTANA DESPEGADA MOD. GDL)", "VDZPC (VENTANA DESPEGADA MOD. ZAP. CHI.)", "VDZPG (VENTANA DESPEGADA MOD. ZAP. GDE.)", "VFZPC (VENTANA FRISIADA MOD. ZAP. CHI.)", "VFZPG (VENTANA FRISIADA MOD. ZAP. GDE.)", "VF (VENTANA FRISIADA MOD. GDL.)", "VR (VENTANA ROTA)", "VRZPC (VENTANA ROTA MOD. ZAP. CHICA)", "VRZPG (VENTANA ROTA MOD. ZAP. GDE.)", "VS (VENTANA SUELTA)", "VRS (VIDRIOS EN EL SISTEMA)" }));

        jlbDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbDescripcion.setForeground(new java.awt.Color(86, 191, 22));
        jlbDescripcion.setText("Descripcion:");

        JtaDescripcion.setColumns(20);
        JtaDescripcion.setRows(5);
        JtaDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtaDescripcionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(JtaDescripcion);

        jbnAgregar.setText("Agregar");
        jbnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAgregarActionPerformed(evt);
            }
        });
        jbnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbnAgregarKeyPressed(evt);
            }
        });

        jbnRegresar.setText("Regresar");
        jbnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnRegresarActionPerformed(evt);
            }
        });
        jbnRegresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbnRegresarKeyPressed(evt);
            }
        });

        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 191, 22)), "Datos de la Actividad"));

        lblUsuarioReporta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblUsuarioReporta.setText("jLabel1");

        txtActividadInfo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtActividadInfo.setText("jLabel1");

        txtCodigoInfo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtCodigoInfo.setText("jLabel1");

        lblDireccionInfo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblDireccionInfo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsuarioReporta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtActividadInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigoInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(lblDireccionInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActividadInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioReporta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccionInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(lblNombreUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlbTipoIncidencias)
                                    .addGap(58, 58, 58)
                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jlbDescripcion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jbnAgregar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jbnRegresar))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(JLBtITULO)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(JLBtITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipoIncidencias)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnRegresar)
                    .addComponent(jbnAgregar))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAgregarActionPerformed
        // TODO add your handling code here:
        String tipo = cmbTipo.getSelectedItem().toString();
        String descripcion = JtaDescripcion.getText().trim();

        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, describe la incidencia.");
            return;
        }

        Controlador.ControladorIncidencias control = new Controlador.ControladorIncidencias();

        if (control.registrarIncidencia(this.idActividadRef, tipo, descripcion, userSesion.getIdUsuario(), this.idUbicacionRef)) {
            JOptionPane.showMessageDialog(this, "¡Incidencia reportada con éxito!");

            MisActividades reporte = new MisActividades(userSesion);
            reporte.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la incidencia. Revisa la consola.");
        }
    }//GEN-LAST:event_jbnAgregarActionPerformed

    private void jbnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnRegresarActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal(userSesion);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnRegresarActionPerformed

    private void JtaDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtaDescripcionKeyPressed
        // TODO add your handling code here:
        char tecla = (char) evt.getExtendedKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            jbnAgregar.requestFocus();
        }
    }//GEN-LAST:event_JtaDescripcionKeyPressed

    private void jbnAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbnAgregarKeyPressed
        // TODO add your handling code here:
        char tecla = (char) evt.getExtendedKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
        jbnAgregar.doClick();
        jbnRegresar.requestFocus();
        }
    }//GEN-LAST:event_jbnAgregarKeyPressed

    private void jbnRegresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbnRegresarKeyPressed
        // TODO add your handling code here:
        char tecla = (char) evt.getExtendedKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            jbnRegresar.doClick();
        }
    }//GEN-LAST:event_jbnRegresarKeyPressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBtITULO;
    private javax.swing.JTextArea JtaDescripcion;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnAgregar;
    private javax.swing.JButton jbnRegresar;
    private javax.swing.JLabel jlbDescripcion;
    private javax.swing.JLabel jlbTipoIncidencias;
    private javax.swing.JLabel lblDireccionInfo;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblUsuarioReporta;
    private javax.swing.JLabel txtActividadInfo;
    private javax.swing.JLabel txtCodigoInfo;
    // End of variables declaration//GEN-END:variables
}
