/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.ClaseUsuario;
import Modelo.ImagenFondo;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ghust
 */
public class Materiales extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Materiales.class.getName());

    /**
     * Creates new form Materiales
     */
    ImagenFondo imgFondo;
    private Modelo.ClaseCampania[] listaCampanias;
    private int idMaterialActual = 0;
     ClaseUsuario userSesion;
     private int idMaterialEdicion = 0;
    public Materiales(ClaseUsuario usuario, Modelo.ClaseMateriales materialAEditar) {
       imgFondo = new ImagenFondo("src/imagenes/FondoFRM.jpg");
    this.setContentPane(imgFondo);
    userSesion = usuario;    
    setSize(900, 550);
    setLocationRelativeTo(null);
    setResizable(false);    
    initComponents();
     lblNombreUsuario.setText("Bienvenido: " + userSesion.getNombre() + " " + userSesion.getApellido() + "  Rol: " + userSesion.getRol());
        String rol = userSesion.getRol();
    cargarComboCampanias(); 

    if (materialAEditar != null) {
        this.idMaterialEdicion = materialAEditar.getIdMaterial();
        txtNombre.setText(materialAEditar.getNombreMaterial());
        cmbTipo.setSelectedItem(materialAEditar.getTipo());
        spnCantidad.setValue(materialAEditar.getCantidadDisponible());
        spnMinimo.setValue(materialAEditar.getStockMinimo());
        if (materialAEditar.getIdCampania() == 0) {
            cmbCampania.setSelectedIndex(0); 
        } else {
            for (int i = 0; i < listaCampanias.length; i++) {
                if (listaCampanias[i].getIdCampania() == materialAEditar.getIdCampania()) {
                    cmbCampania.setSelectedIndex(i + 1);
                    break;
                }
            }
        }

        btnAgregar.setText("Actualizar Material");
        this.setTitle("Modificar Material");
    } else {
        this.idMaterialEdicion = 0;
        btnAgregar.setText("Guardar Material");
        this.setTitle("Agregar Nuevo Material");
    }
        
    }
    
    private void cargarComboCampanias() {
    cmbCampania.removeAllItems();
    cmbCampania.addItem("---");
    
    Controlador.ControladorCampanias control = new Controlador.ControladorCampanias();
    this.listaCampanias = control.leerCampanias();
    
    if (this.listaCampanias != null) {
        for (Modelo.ClaseCampania c : this.listaCampanias) {
            cmbCampania.addItem(c.getNombre());
        }
    }
}
    
    private void limpiarCampos() {
    txtNombre.setText("");
    jTextArea1.setText(""); 
    cmbTipo.setSelectedIndex(0);
    cmbCampania.setSelectedIndex(0);
    spnCantidad.setValue(0);
    spnMinimo.setValue(0);
    txtNombre.requestFocus();
    this.idMaterialEdicion = 0;
    btnAgregar.setText("Guardar Material");
    this.setTitle("Agregar Nuevo Material");
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jlbMaterial = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbnVolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        cmbCampania = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        spnMinimo = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 138, 25));
        jLabel6.setText("Tipo:");

        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(86, 191, 22), null));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARTE", "HERRAMIENTA", "ELECTRICO", "ESTRUCTURA", "OTRO" }));
        cmbTipo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(86, 191, 22), null));
        cmbTipo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        btnAgregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAgregarKeyPressed(evt);
            }
        });

        jlbMaterial.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        jlbMaterial.setForeground(new java.awt.Color(68, 138, 25));
        jlbMaterial.setText("MATERIAL");

        jlbNombre.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jlbNombre.setForeground(new java.awt.Color(68, 138, 25));
        jlbNombre.setText("Nombre:");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jbnVolver.setText("Volver");
        jbnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnVolverActionPerformed(evt);
            }
        });
        jbnVolver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbnVolverKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 138, 25));
        jLabel5.setText("Campaña (opcional)");

        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("jLabel7");

        cmbCampania.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 138, 25));
        jLabel7.setText("Cantidad disponible");

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(68, 138, 25));
        jLabel8.setText("Stock minimo");

        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 138, 25));
        jLabel9.setText("Descripcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblNombreUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jlbNombre)
                                                    .addComponent(jLabel6))
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jlbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spnMinimo)
                                    .addComponent(cmbCampania, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spnCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                .addGap(223, 223, 223))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(btnAgregar)
                                        .addGap(271, 271, 271)
                                        .addComponent(jbnVolver))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jlbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCampania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jbnVolver))
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jbnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnVolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal(this.userSesion);
          menu.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jbnVolverActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    if (txtNombre.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre del material es obligatorio.");
        return;
    }

    Modelo.ClaseMateriales mat = new Modelo.ClaseMateriales();
    mat.setNombreMaterial(txtNombre.getText().trim().toUpperCase());
    mat.setTipo(cmbTipo.getSelectedItem().toString());
    mat.setCantidadDisponible((int) spnCantidad.getValue());
    mat.setStockMinimo((int) spnMinimo.getValue());

    if (cmbCampania.getSelectedIndex() > 0) {
        int idC = listaCampanias[cmbCampania.getSelectedIndex() - 1].getIdCampania();
        mat.setIdCampania(idC);
    } else {
        mat.setIdCampania(0);
    }
    Controlador.ControladorMaterial control = new Controlador.ControladorMaterial();

    if (this.idMaterialEdicion == 0) {
        if (control.registrarMaterial(mat)) {
            JOptionPane.showMessageDialog(this, "Material registrado exitosamente.");
            limpiarCampos();
        }
    } else {
        mat.setIdMaterial(this.idMaterialEdicion); 
        if (control.modificarMaterial(mat)) {
            JOptionPane.showMessageDialog(this, "Material actualizado exitosamente.");
            ReporteMaterial repmat = new ReporteMaterial(userSesion);
            repmat.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al intentar actualizar el material.");
        }
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
        char tecla = (char) evt.getExtendedKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            jTextArea1.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
        char tecla = (char) evt.getExtendedKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            btnAgregar.requestFocus();
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void btnAgregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAgregarKeyPressed
        // TODO add your handling code here:
        char tecla = (char) evt.getExtendedKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            btnAgregar.doClick();
            jbnVolver.requestFocus();
        }
    }//GEN-LAST:event_btnAgregarKeyPressed

    private void jbnVolverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbnVolverKeyPressed
        // TODO add your handling code here:
        char tecla = (char) evt.getExtendedKeyCode();
        if (tecla == KeyEvent.VK_ENTER) {
            jbnVolver.doClick();
        }
    }//GEN-LAST:event_jbnVolverKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Materiales(null, null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbCampania;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbnVolver;
    private javax.swing.JLabel jlbMaterial;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JSpinner spnMinimo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
