/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorActividad;
import Modelo.ClaseUsuario;
import Modelo.ImagenFondo;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;

/**
 *
 * @author ghust
 */
public class MenuReportes extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuReportes.class.getName());

    /**
     * Creates new form ReporteActividades
     */
    ClaseUsuario userSesion;
    ImagenFondo imgFondo;

    public MenuReportes(ClaseUsuario usuario) {
        userSesion = usuario;
        imgFondo = new ImagenFondo("src/imagenes/FondoFRM.jpg");
        this.setContentPane(imgFondo);
        initComponents();
        setSize(900, 550);
        setLocationRelativeTo(null);
        setResizable(false);
        lblNombreUsuario.setText("Bienvenido: " + userSesion.getNombre() + " " + userSesion.getApellido() + "  Rol: " + userSesion.getRol());
        configurarBoton(BtnRepIncidencias, "Reportes "
                + "de incidencias", "/Imagenes/REPORTES DE INCIDENCIA.png");
        configurarBoton(BtnRepCampañas,  "Reportes "
                + "de campañas", "/Imagenes/REPORTES DE CAMPAÑAS.png");
        configurarBoton(BtnRepUbicaciones,  "Reportes "
                + "de ubicaciones", "/Imagenes/REPORTE UBICACIONES.png");
        configurarBoton(BtnRepUsuarios,  "Reportes "
                + "de usuarios", "/Imagenes/REPORTE USUARIOS.png");
         configurarBoton(BtnRepProdu,  "Reportes "
                + "de productividad", "/Imagenes/REPORTE PRODUCTIVIDAD.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbnVolver = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        BtnRepIncidencias = new javax.swing.JButton();
        BtnRepCampañas = new javax.swing.JButton();
        BtnRepUbicaciones = new javax.swing.JButton();
        BtnRepUsuarios = new javax.swing.JButton();
        BtnRepProdu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 138, 25));
        jLabel1.setText("MENU DE REPORTES");

        jbnVolver.setText("Volver");
        jbnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnVolverActionPerformed(evt);
            }
        });

        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("jLabel2");

        BtnRepIncidencias.setText("jButton1");
        BtnRepIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepIncidenciasActionPerformed(evt);
            }
        });

        BtnRepCampañas.setText("jButton2");
        BtnRepCampañas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepCampañasActionPerformed(evt);
            }
        });

        BtnRepUbicaciones.setText("jButton3");
        BtnRepUbicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepUbicacionesActionPerformed(evt);
            }
        });

        BtnRepUsuarios.setText("jButton4");
        BtnRepUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepUsuariosActionPerformed(evt);
            }
        });

        BtnRepProdu.setText("jButton1");
        BtnRepProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRepProduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblNombreUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BtnRepIncidencias)
                                    .addGap(72, 72, 72)
                                    .addComponent(BtnRepProdu)
                                    .addGap(75, 75, 75)
                                    .addComponent(BtnRepCampañas))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(BtnRepUbicaciones)
                                    .addGap(104, 104, 104)
                                    .addComponent(BtnRepUsuarios)
                                    .addGap(30, 30, 30)))
                            .addComponent(jLabel1))))
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbnVolver)
                .addGap(380, 380, 380))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblNombreUsuario)
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRepIncidencias)
                    .addComponent(BtnRepCampañas)
                    .addComponent(BtnRepProdu))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRepUbicaciones)
                    .addComponent(BtnRepUsuarios))
                .addGap(61, 61, 61)
                .addComponent(jbnVolver)
                .addGap(102, 102, 102))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnVolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal(this.userSesion);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnVolverActionPerformed

    private void BtnRepUbicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepUbicacionesActionPerformed
        // TODO add your handling code here:
        ReporteUbicaciones repU = new ReporteUbicaciones(userSesion);
        repU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRepUbicacionesActionPerformed

    private void BtnRepIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepIncidenciasActionPerformed
        // TODO add your handling code here:
        ReporteIncidencias repIn = new ReporteIncidencias(userSesion);
        repIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRepIncidenciasActionPerformed

    private void BtnRepProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepProduActionPerformed
        // TODO add your handling code here:
        ReporteProductividad repp = new ReporteProductividad(userSesion);
        repp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRepProduActionPerformed

    private void BtnRepCampañasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepCampañasActionPerformed
        // TODO add your handling code here:
        ReporteCampania repC = new ReporteCampania(userSesion);
        repC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRepCampañasActionPerformed

    private void BtnRepUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRepUsuariosActionPerformed
        // TODO add your handling code here:
        ReporteUsuarios repusu = new ReporteUsuarios(userSesion);
        repusu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRepUsuariosActionPerformed
    private void configurarBoton(JButton boton, String texto, String icono) {
        boton.setText(texto);
        boton.setIcon(new ImageIcon(getClass().getResource(icono)));
        boton.setHorizontalTextPosition(SwingConstants.CENTER);
        boton.setVerticalTextPosition(SwingConstants.BOTTOM);
        boton.setIconTextGap(10);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuReportes(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRepCampañas;
    private javax.swing.JButton BtnRepIncidencias;
    private javax.swing.JButton BtnRepProdu;
    private javax.swing.JButton BtnRepUbicaciones;
    private javax.swing.JButton BtnRepUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbnVolver;
    private javax.swing.JLabel lblNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
