/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorMaterial;
import Modelo.ClaseMateriales;
import Modelo.ClaseUsuario;
import Modelo.ImagenFondo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ghust
 */
public class ReporteMaterial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReporteMaterial.class.getName());

    /**
     * Creates new form ReporteMaterial
     */
    ImagenFondo imgFondo;
    private Modelo.ClaseMateriales[] listaLocal;
     ClaseUsuario userSesion;
     private ControladorMaterial controlMat = new ControladorMaterial();
    public ReporteMaterial(ClaseUsuario usuario) {
        imgFondo = new ImagenFondo("src/imagenes/FondoFRM.jpg");
        this.setContentPane(imgFondo);
        setSize(900, 550);
        setLocationRelativeTo(null);
        setResizable(false);
        userSesion =  usuario;
        initComponents();
        configurarInterfazPorRol();
        cargarTabla();
         lblNombreUsuario.setText("Bienvenido: " + userSesion.getNombre() + " " + userSesion.getApellido() + "  Rol: " + userSesion.getRol());
        String rol = userSesion.getRol();
    }
     private void configurarInterfazPorRol() {
        if (userSesion == null) {
            return;
        }
        lblNombreUsuario.setText("Bienvenido: " + userSesion.getNombre() + " " + userSesion.getApellido() + "  Rol: " + userSesion.getRol());
        String rol = userSesion.getRol();

        if (rol.equals("ALMACENISTA")) {
            verificarAlertasStock();
         }
        if (rol.equals("SUPERVISOR")) {
            verificarAlertasStock();
     }}
    
     private void verificarAlertasStock() {
        ClaseMateriales[] bajos = controlMat.consultarStockBajo();

        if (bajos != null && bajos.length > 0) {
            StringBuilder mensaje = new StringBuilder();
            mensaje.append("<html><body style='width: 250px;'>");
            mensaje.append("<h2 style='color:red;'>⚠️ ALERTA DE STOCK BAJO</h2>");
            mensaje.append("<p>Los siguientes materiales están por debajo del mínimo:</p><ul>");

            for (ClaseMateriales m : bajos) {
                mensaje.append("<li><b>").append(m.getNombreMaterial()).append("</b>")
                        .append("<br>Disponible: <span style='color:red;'>").append(m.getCantidadDisponible()).append("</span>")
                        .append(" (Mín: ").append(m.getStockMinimo()).append(")</li><br>");
            }

            mensaje.append("</ul></body></html>");

            JOptionPane.showMessageDialog(this, mensaje.toString(), "Sistema de Almacén IMU", JOptionPane.WARNING_MESSAGE);
        }
    }
public void cargarTabla() {
    Controlador.ControladorMaterial control = new Controlador.ControladorMaterial();
    this.listaLocal = control.leerTodosLosMateriales();
    
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Tipo");
    modelo.addColumn("Stock");
    modelo.addColumn("Mínimo");
    modelo.addColumn("Estado"); // Para poner si falta material

    if (listaLocal != null) {
        for (Modelo.ClaseMateriales m : listaLocal) {
            String estado = (m.getCantidadDisponible() <= m.getStockMinimo()) ? "BAJO STOCK" : "OK";
            modelo.addRow(new Object[]{
                m.getIdMaterial(),
                m.getNombreMaterial(),
                m.getTipo(),
                m.getCantidadDisponible(),
                m.getStockMinimo(),
                estado
            });
        }
    }
    tblMateriales.setModel(modelo);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbnVolver = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMateriales = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 138, 25));
        jLabel1.setText("REPORTE DE MATERIALES");

        jbnVolver.setText("Volver");
        jbnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnVolverActionPerformed(evt);
            }
        });

        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("jLabel1");

        tblMateriales.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(41, 112, 172), null));
        tblMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Registro", "Actividad", "Material", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(tblMateriales);

        jButton1.setText("Editar Stock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jbnVolver)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(lblNombreUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnVolver)
                    .addComponent(jButton1))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila = tblMateriales.getSelectedRow();
    
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un material de la tabla.");
        return;
    }

    int idBuscado = Integer.parseInt(tblMateriales.getValueAt(fila, 0).toString());
    Modelo.ClaseMateriales materialSeleccionado = null;
    for (Modelo.ClaseMateriales m : listaLocal) {
        if (m.getIdMaterial() == idBuscado) {
            materialSeleccionado = m;
            break;
        }
    }
    Materiales ventanaEditar = new Materiales(userSesion, materialSeleccionado);
    ventanaEditar.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnVolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal(userSesion);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReporteMaterial(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbnVolver;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JTable tblMateriales;
    // End of variables declaration//GEN-END:variables
}
