/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorActividad;
import Controlador.ControladorIncidencias;
import Modelo.ClaseUsuario;
import Modelo.ImagenFondo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ghust
 */
public class ReporteIncidencias extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReporteIncidencias.class.getName());

    /**
     * Creates new form ReporteActividades
     */
    ClaseUsuario userSesion;
    ImagenFondo imgFondo;

    public ReporteIncidencias(ClaseUsuario usuario) {
        userSesion = usuario;
        imgFondo = new ImagenFondo("src/imagenes/FondoFRM.jpg");
        this.setContentPane(imgFondo);
        initComponents();
        cargarTabla();
        setSize(900, 550);
        setLocationRelativeTo(null);
        setResizable(false);
        lblNombreUsuario.setText("Bienvenido: " + userSesion.getNombre() + " " + userSesion.getApellido() + "  Rol: " + userSesion.getRol());
    }

 private void cargarTabla() {
    // 1. Definición del modelo de la tabla
    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    modelo.addColumn("ID");          // Columna 0
    modelo.addColumn("Tipo");        // Columna 1
    modelo.addColumn("Ubicación");   // Columna 2
    modelo.addColumn("Descripción"); // Columna 3
    modelo.addColumn("Estado");      // Columna 4
    modelo.addColumn("idUsuOculto"); // Columna 5

    // 2. Obtención de datos desde el controlador
    Controlador.ControladorIncidencias control = new Controlador.ControladorIncidencias();
    Object[][] todas = control.leerTodasLasIncidencias();

    if (todas != null) {
        for (Object[] fila : todas) {
            int idUsuarioFila = 0;
            if (fila[5] != null) {
                idUsuarioFila = Integer.parseInt(fila[5].toString());
            }

            // Lógica de filtrado por Rol
            if ("ASOCIADO".equalsIgnoreCase(userSesion.getRol())) {
                // Si es asociado, solo añadimos si el ID coincide
                if (idUsuarioFila == userSesion.getIdUsuario()) {
                    modelo.addRow(fila);
                }
            } else {
                // Si es Supervisor o Admin, añadimos todo
                modelo.addRow(fila);
            }
        }
    }

    // 4. Asignar el modelo a la tabla
    tblIncidencias.setModel(modelo);

    tblIncidencias.getColumnModel().getColumn(0).setMinWidth(0);
    tblIncidencias.getColumnModel().getColumn(0).setMaxWidth(0);
    tblIncidencias.getColumnModel().getColumn(0).setPreferredWidth(0);
    tblIncidencias.getColumnModel().getColumn(5).setMinWidth(0);
    tblIncidencias.getColumnModel().getColumn(5).setMaxWidth(0);
    tblIncidencias.getColumnModel().getColumn(5).setPreferredWidth(0);
    tblIncidencias.getColumnModel().getColumn(1).setPreferredWidth(100); // Tipo
    tblIncidencias.getColumnModel().getColumn(2).setPreferredWidth(250); // Ubicación (Calles)
    tblIncidencias.getColumnModel().getColumn(3).setPreferredWidth(350); // Descripción (Más ancho)
    tblIncidencias.getColumnModel().getColumn(4).setPreferredWidth(100); // Estado
    tblIncidencias.revalidate();
    tblIncidencias.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblIncidencias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbnIncidencias = new javax.swing.JButton();
        jbnVolver = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tblIncidencias.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(41, 112, 172), null));
        tblIncidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuario", "Actividad", "Ubicacion", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblIncidencias);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 138, 25));
        jLabel1.setText("REPORTE DE PRODUCTIVIDAD");

        jbnIncidencias.setText("Nueva Incidencia");

        jbnVolver.setText("Volver");
        jbnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnVolverActionPerformed(evt);
            }
        });

        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jbnIncidencias)
                        .addGap(65, 65, 65)
                        .addComponent(jbnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblNombreUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnIncidencias)
                    .addComponent(jbnVolver))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnVolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal(this.userSesion);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReporteIncidencias(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnIncidencias;
    private javax.swing.JButton jbnVolver;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JTable tblIncidencias;
    // End of variables declaration//GEN-END:variables
}
